import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  DynamicEnvironmentId,
  DynamicContextProvider,
  EthereumWalletConnectors,
  EthersExtension
} from "@/utils/Dynamic";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: DynamicEnvironmentId,
          walletConnectors: [EthereumWalletConnectors],
          walletConnectorExtensions: [EthersExtension],
          appName: "BLOX",
          appLogoUrl:
            "@/assets/blox400.jpg",
          privacyPolicyUrl: "/privacy-policy",
          termsOfServiceUrl: "/terms-of-service",
        }}
      >
        <body className={inter.className}>{children}</body>
      </DynamicContextProvider>
    </html>
  );
}
